// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03NIu3HlH18Lu5bvPMAlD2NY-LrcI-y4',
    appId: '1:381894296365:web:27ddab817d1246a81389a4',
    messagingSenderId: '381894296365',
    projectId: 'titok-1c1a5',
    authDomain: 'titok-1c1a5.firebaseapp.com',
    storageBucket: 'titok-1c1a5.firebasestorage.app',
    measurementId: 'G-DQE2Q703JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsjFEqwy_soptIPatMm0vlmv5W2fZ2iJc',
    appId: '1:381894296365:android:bfd3e7039cfc4f851389a4',
    messagingSenderId: '381894296365',
    projectId: 'titok-1c1a5',
    storageBucket: 'titok-1c1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EllKK0-wDSPnZrKyrXIilXvDqtFBbKg',
    appId: '1:381894296365:ios:9d6121a5065ca1f61389a4',
    messagingSenderId: '381894296365',
    projectId: 'titok-1c1a5',
    storageBucket: 'titok-1c1a5.firebasestorage.app',
    iosBundleId: 'com.example.foodpanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EllKK0-wDSPnZrKyrXIilXvDqtFBbKg',
    appId: '1:381894296365:ios:9d6121a5065ca1f61389a4',
    messagingSenderId: '381894296365',
    projectId: 'titok-1c1a5',
    storageBucket: 'titok-1c1a5.firebasestorage.app',
    iosBundleId: 'com.example.foodpanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA03NIu3HlH18Lu5bvPMAlD2NY-LrcI-y4',
    appId: '1:381894296365:web:6e40e8df68549b401389a4',
    messagingSenderId: '381894296365',
    projectId: 'titok-1c1a5',
    authDomain: 'titok-1c1a5.firebaseapp.com',
    storageBucket: 'titok-1c1a5.firebasestorage.app',
    measurementId: 'G-8JJKB0XM1D',
  );
}
